version: '3.7'
services:
  
  nginx:
    #init is to not have any zombie child-processes (exits well when you send SIGINT)
    init: true
    build:
      context: ./srcs/nginx
    volumes:
      - "php_nginx:/var/www/html"
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - my_net
    depends_on:
      - mariadb
    env_file:
      - .env

  php:
    init: true
    build:
      context: ./srcs/php
    volumes:
      - "php_nginx:/var/www/html"
    restart: always
    networks:
      - my_net
    env_file:
      - .env
    depends_on:
        - mariadb

  mariadb:
    init: true
    build:
      context: ./srcs/mariadb
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: mariadb:3306
    volumes:
      - "db_volume:/var/lib/mysql/"
    restart: always
    networks:
      - my_net


networks:
  my_net:

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/tedison/Documents/data/db_volume
  php_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/tedison/Documents/data/volume_phpnginx
